apiVersion: v1
kind: Service
metadata:
  labels:
    app: temporal-trivia-worker
  name: metrics
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: temporal-trivia-worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}